### ISSUE TITLE
New Recipe of Books

### ISSUE THREAD

**Issue by albertosaurio65** [oierbravo/create-paper-line#3]
A new method for creating the books could be made to further automate the creation of books with create

You have already implemented the paper, but what if the book cover is created separately?

I would agree on another assembly line to create the books and then put the cover together with the paper to create the book

It could be done with a new "animation", by placing only the cover on a conveyor belt, it appears open, and with mechanical arms or deployer sheets of paper would be inserted up to the amount you put for the recipe

**Comment by oierbravo** [comment]
Hi!
The book cover is already implemented. It's made of cardboard in a separate line.
For the complete book there is also an assembly line.

thanks for the suggestion anyway.

**Comment by oierbravo** [comment]
I just uploaded an example schematic with the full production line.
[](https://github.com/oierbravo/create-paper-line/raw/main/example_schematics/production_line_test.nbt)

It's in the `example_schematics` folders.

**Comment by albertosaurio65** [comment]
I had seen the cardboard in the lang, but nothing about it appeared in the game

**Comment by albertosaurio65** [comment]
I just checked it and I'm totally blind, I didn't even realize that the two sheets appeared and what they were for, sorry

**Comment by albertosaurio65** [comment]
> I just uploaded an example schematic with the full production line. https://github.com/oierbravo/create-paper-line/raw/main/example_schematics/production_line_test.nbt



![image](https://github.com/oierbravo/create-paper-line/assets/70109413/1cb23d58-5038-4c2c-a45a-2d77ef53d7a4)
![image](https://github.com/oierbravo/create-paper-line/assets/70109413/ebff9ec5-5c5e-4977-8d87-b5e7fb74078e)

Create adds a recipe so that sticks come out when crushing the logs, there is also yours but it gives preference to sticks, the solution I have is to put the small crusher, do you know if it is possible to choose the recipe on the large crusher wheels?

**Comment by oierbravo** [comment]
As I know... Create by itself doesn't have en crushing/milling recipe for wood.
If you toggle Adavanced tooltips with `F3 + H` you can see which mod adds the recipe.

**Comment by albertosaurio65** [comment]
okey, when I saw the sticks recipe it said recipe added by create but I think it's going to be a create recycling mod

I will review it later with that of the f3

**Comment by oierbravo** [comment]
oki!! thx!

**Comment by albertosaurio65** [comment]
![image](https://github.com/oierbravo/create-paper-line/assets/70109413/92a3d508-67b4-4ac3-8cc8-dfd12f24dca1)

I already had f3 + H activated, that's why I told you to add it to create, but I still think it's a matter of https://www.curseforge.com/minecraft/mc-mods/create-recycle-everything

**Comment by oierbravo** [comment]
Yes! It's Create Recycle Everything
Looked inside the mods jar...
![Screenshot_20230811_141043](https://github.com/oierbravo/create-paper-line/assets/708317/7840ed5d-3d46-4389-93d7-a2e0a2abba28)

I'm looking for a way to mitigate this issue.
Thanks!

**Comment by albertosaurio65** [comment]
Okey, thanks you for the mod and everything ( are you spanish or a italian who know a little spanish?)

**Comment by oierbravo** [comment]
Spanish.

**Comment by albertosaurio65** [comment]
Y porqué hablamos en inglés xd

**Comment by albertosaurio65** [comment]
Por cierto, si no quieres tomarte la molestia de un discord entero para el mod hay un discord que es un HUB donde hay varios creadores de mods, igual pueden añadir el tuyo https://discord.gg/SsqfCj7z

**Comment by oierbravo** [comment]
Aunque este es el 3 addon para Create (+ varios en camino) y tengo algún mod más no me da la vida para discord. Requiere mucha paciencia, tiempo y energía las cuales me quitan de lo que más me mola que es crear los mods.

He preferido mantener cada mod en github y usar las issues para todo.
Por esto mismo suelo contestar todo en ingles (lo mejor que puedo) asi que cualquiera que venga pueda entender y leer todo.

Muchas gracias por la idea igualmente.

**Comment by albertosaurio65** [comment]
Oki, no pasa na, suerte con tus proyectos
